# ===== experiment info =====
note: disease_inceptionv3_baseline
work_dir: work_dir

# ===== dataset =====
dataset_root: ../BDShrimp
#dataset_root: ../TigerShrimpBD
num_classes: 4
label_map:
  healthy: 0
  wssv: 1
  bg: 2
  wssv_bg: 3
#  yellowhead: 3

# ===== 5-fold CV =====
cv_seed: 42
n_folds: 5

# ===== model switches =====
use_T: false
use_R: false
use_dirichlet: false
use_T_eval: false
use_R_eval: false
backbone: inception_v3

# ===== training =====
epochs: 50
lr: 1e-6
lambda_conf: 0.5
lambda_risk: 0.5

# ===== early stopping =====
es_monitor: macro_f1
es_mode: max
es_patience: 3
es_min_delta: 1e-3
es_min_epoch: 10
